# Generated by Django 4.2.2 on 2023-06-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descirption',
            new_name='description',
        ),
    ]
