# Generated by Django 4.2.2 on 2023-06-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
